In [14]:
import numpy as np
import matplotlib as plt
arr=np.array([[5,4,3,2,1],[1,2,3,4,5]])
print(arr)
print(f"{arr.ndim}")
print(f"{arr.shape}")
print(f"{arr.size}")
print(f"{arr.dtype}")
print(f"{arr.itemsize}")
print(arr.T)
print(arr)


[[5 4 3 2 1]
 [1 2 3 4 5]]
2
(2, 5)
10
int64
8
[[5 1]
 [4 2]
 [3 3]
 [2 4]
 [1 5]]
[[5 4 3 2 1]
 [1 2 3 4 5]]
